### ISSUE TITLE
Implement static formatting toolbar 

### ISSUE THREAD

**Issue by vinay0x** [bigbinary/neeto-editor#12]
@vinay0x _a

**Comment by edwinbbu** [comment]
@labeebklatif _a

**Comment by edwinbbu** [comment]
Ref:
<img width="1776" alt="Screenshot 2021-10-21 at 3 53 08 PM" src="https://user-images.githubusercontent.com/17916573/138259416-fdc74ae7-5aad-4063-8ba9-352691c627a5.png">

**Comment by edwinbbu** [comment]
Ref: https://tiptap.dev/examples/default
