### ISSUE TITLE
Add Screen for Testing the Neeto Editor

### ISSUE THREAD

**Issue by philson-philip** [bigbinary/neeto-editor#3]
@edwinbbu Can you add a screen for testing the package as we have discussed during the call?

**Comment by edwinbbu** [comment]
Added development screen.
<img width="1792" alt="Screenshot 2021-04-23 at 7 05 54 PM" src="https://user-images.githubusercontent.com/17916573/115879226-0ce73d80-a467-11eb-9d02-8ad6730ce5a3.png">
